### ISSUE TITLE
TypeError and performance issues with large dataset

### ISSUE THREAD

**Issue by walid0925** [lmcinnes/umap#401] opened 2020-04-13 20:29 UTC
Hi, thanks so much for the time you've invested in developing this project!

I'm working with a fairly large dataset, 1.75M samples in total, using binary vectors with 2048 elements each. When using on the order of 10k samples, I have no issues with this:
```
mapper = umap.UMAP(metric='jaccard', n_neighbors=5, low_memory=True, min_dist=0.001)
um = mapper.fit_transform(data)
```

However, when using 100k samples, I receive the following error (happens irrespective of `low_memory` and with multiple metrics, such as cosine) :
```
~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in _pairwise_callable(X, Y, metric, force_all_finite, **kwds)
   1373         iterator = itertools.combinations(range(X.shape[0]), 2)
   1374         for i, j in iterator:
-> 1375             out[i, j] = metric(X[i], Y[j], **kwds)
   1376 
   1377         # Make symmetric

TypeError: not enough arguments: expected 4, got 2
```

I'm storing my data in a `scipy.sparse` matrix:
```
<100000x2048 sparse matrix of type '<class 'numpy.float32'>'
	with 4878596 stored elements in Compressed Sparse Row format>
```

<details>
<summary>Full traceback</summary>

```
/home/ubuntu/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/umap_.py:1529: UserWarning: gradient function is not yet implemented for jaccard distance metric; inverse_transform will be unavailable
  "inverse_transform will be unavailable".format(self.metric)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/umap_.py in fit_transform(self, X, y)
   1966             Embedding of the training data in low-dimensional space.
   1967         """
-> 1968         self.fit(X, y)
   1969         return self.embedding_
   1970 

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/umap_.py in fit(self, X, y)
   1935             self.output_metric in ("euclidean", "l2"),
   1936             self.random_state is None,
-> 1937             self.verbose,
   1938         )[inverse]
   1939 

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/umap_.py in simplicial_set_embedding(data, graph, n_components, initial_alpha, a, b, gamma, negative_sample_rate, n_epochs, init, random_state, metric, metric_kwds, output_metric, output_metric_kwds, euclidean_output, parallel, verbose)
   1036             random_state,
   1037             metric=metric,
-> 1038             metric_kwds=metric_kwds,
   1039         )
   1040         expansion = 10.0 / np.abs(initialisation).max()

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/spectral.py in spectral_layout(data, graph, dim, random_state, metric, metric_kwds)
    279             random_state,
    280             metric=metric,
--> 281             metric_kwds=metric_kwds,
    282         )
    283 

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/spectral.py in multi_component_layout(data, graph, n_components, component_labels, dim, random_state, metric, metric_kwds)
    166             random_state,
    167             metric=metric,
--> 168             metric_kwds=metric_kwds,
    169         )
    170     else:

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/umap/spectral.py in component_layout(data, n_components, component_labels, dim, random_state, metric, metric_kwds)
     95         else:
     96             distance_matrix = pairwise_distances(
---> 97                 component_centroids, metric=metric, **metric_kwds
     98             )
     99 

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in pairwise_distances(X, Y, metric, n_jobs, force_all_finite, **kwds)
   1750         func = partial(distance.cdist, metric=metric, **kwds)
   1751 
-> 1752     return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1753 
   1754 

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1346 
   1347     if effective_n_jobs(n_jobs) == 1:
-> 1348         return func(X, Y, **kwds)
   1349 
   1350     # enforce a threading backend to prevent data communication overhead

~/miniconda3/envs/reverie_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in _pairwise_callable(X, Y, metric, force_all_finite, **kwds)
   1373         iterator = itertools.combinations(range(X.shape[0]), 2)
   1374         for i, j in iterator:
-> 1375             out[i, j] = metric(X[i], Y[j], **kwds)
   1376 
   1377         # Make symmetric

TypeError: not enough arguments: expected 4, got 
```

</details>

<details>
<summary> Environment details</summary>

```
numba                     0.48.0                   pypi_0    pypi
numpy                     1.18.2                   pypi_0    pypi
scikit-learn              0.22.2.post1             pypi_0    pypi
tbb                       2020.0.133               pypi_0    pypi
umap-learn                0.4.1                    pypi_0    pypi
```

`umap-learn` was pip-installed from the git repo directly on 4/10/20
</details>

---

I've also noticed that when running `.fit_transform()` one core is utilized for a long period of time, particularly when the number of neighbors (or samples) increases (I'm guessing this might be the phase when KNN is being used?). After some time, all cores become active, which is what happens when just `.transform()` is run. I was wondering 1) is this expected behavior? and 2) is there any way to parallelize that slower initial phase?

I'm relatively new to this code so apologies if these issues have already been discussed, I did my best to browse through open issues first but didn't find a conclusive answer. Thank you!

**Comment by lmcinnes** [comment] 2020-04-14 19:55
The first error is, I suspect, a minor issue in how the spectral initialization gets handled when working with sparse data. You can either use ``init='random'`` or a larger ``n_neighbors`` value to get around it for now. I'll try to get a fix written soon.

As for the other issue with parallelism ... it turns out that yes there is something you can do to speed-up/parallelise the nearest neighbor search phase. Most of the work on that went into a new library devoted to just that problem called pynndescent. That library includes a parallel version. To enable that in UMAP you just need to install the pynndescent library
```
pip install pynndescent
```
or 
```
conda install -c conda-forge pynndescent
```
and, assuming you are using the 0.4 release of UMAP,  it will automatically use pynndescent once it is installed and you should get decent parallel performance.

**Comment by walid0925** [comment] 2020-04-15 16:51
Thanks very much! Increasing `n_neighbors` did the trick and `pynndescent` also solved the multiprocessing issue with quite a significant speedup.

**Comment by lmcinnes** [comment] 2020-04-15 18:03
Glad it worked out. I'll close this for now.

**Closed by lmcinnes** 2020-04-15 18:03 UTC

**Comment by dkobak** [comment] 2020-05-04 23:36
I have the same issue. Here is a reproducible example.

I am running `UMAP 0.4.2, pynndescent 0.4.7, numba 0.46.0`. The following code works fine:

```
A = scipy.sparse.csr_matrix((np.random.randn(1000,100) > 3).astype(float))
UMAP(metric='cosine').fit_transform(A)
```

but if the number of rows is increased to 10000, I get an error:

```
A = scipy.sparse.csr_matrix((np.random.randn(10000,100) > 3).astype(float))
UMAP(metric='cosine').fit_transform(A)
```

Here is the error:

```
~/anaconda3/envs/sonic/lib/python3.7/site-packages/umap/spectral.py in component_layout(data, n_components, component_labels, dim, random_state, metric, metric_kwds)
     95         else:
     96             distance_matrix = pairwise_distances(
---> 97                 component_centroids, metric=metric, **metric_kwds
     98             )
     99 

~/anaconda3/envs/sonic/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in pairwise_distances(X, Y, metric, n_jobs, force_all_finite, **kwds)
   1750         func = partial(distance.cdist, metric=metric, **kwds)
   1751 
-> 1752     return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1753 
   1754 

~/anaconda3/envs/sonic/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1346 
   1347     if effective_n_jobs(n_jobs) == 1:
-> 1348         return func(X, Y, **kwds)
   1349 
   1350     # enforce a threading backend to prevent data communication overhead

~/anaconda3/envs/sonic/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in _pairwise_callable(X, Y, metric, force_all_finite, **kwds)
   1373         iterator = itertools.combinations(range(X.shape[0]), 2)
   1374         for i, j in iterator:
-> 1375             out[i, j] = metric(X[i], Y[j], **kwds)
   1376 
   1377         # Make symmetric

TypeError: not enough arguments: expected 4, got 2
```

**Comment by lmcinnes** [comment] 2020-05-06 03:57
Hmm, I thought I caught all the ways this could end up getting triggered. I'll have to see if I can hunt down what it happening here.

**Comment by lmcinnes** [comment] 2020-05-07 18:14
Ah, I think I see the problem -- the data is sparse enough that some of the component centroids are still sparse, and that can break things. I think this will fix things. In principle you could blow your memory on this if you have very high dimensional data with a lot of components. I've added a warning to hopefully catch that and suggest ways around it.

**Comment by dkobak** [comment] 2020-05-07 23:44
Thanks for looking into it! But does this snippet work for you with this fix?

```
A = scipy.sparse.csr_matrix((np.random.randn(10000,100) > 3).astype(float))
UMAP(metric='cosine', verbose=1).fit_transform(A)
```

I implemented your fix locally but I still get the same error.

**Comment by dkobak** [comment] 2020-05-07 23:53
I tried to look into why the same snippet with 1000 rows does work, but it seems the `component_layout()` function does not get executed at all in this case? Not sure why.

```
A = scipy.sparse.csr_matrix((np.random.randn(1000,100) > 3).astype(float))
UMAP(metric='cosine').fit_transform(A)
```

**Comment by lmcinnes** [comment] 2020-05-08 01:44
Alright, I think I see the alternative path. Hopefully [this](https://github.com/lmcinnes/umap/commit/5496bea60a24e340b584b9c21dcc1eaf5f50d48d) will address that problem.

**Comment by dkobak** [comment] 2020-05-08 09:33
Now I get a different error:

```
~/anaconda3/envs/sonic/lib/python3.7/site-packages/umap/spectral.py in component_layout(data, n_components, component_labels, dim, random_state, metric, metric_kwds)
    105                 metric
    106             ) == numba.targets.registry.CPUDispatcher and scipy.sparse.isspmatrix(data):
--> 107                 function_to_name_mapping = {v: k for k, v in sparse_named_distances}
    108                 try:
    109                     metric_name = function_to_name_mapping[metric]

~/anaconda3/envs/sonic/lib/python3.7/site-packages/umap/spectral.py in <dictcomp>(.0)
    105                 metric
    106             ) == numba.targets.registry.CPUDispatcher and scipy.sparse.isspmatrix(data):
--> 107                 function_to_name_mapping = {v: k for k, v in sparse_named_distances}
    108                 try:
    109                     metric_name = function_to_name_mapping[metric]

ValueError: too many values to unpack (expected 2)
```

Should it be
```
                function_to_name_mapping = {sparse_named_distances[k]: k for k in sparse_named_distances}
```
?

**Comment by dkobak** [comment] 2020-05-15 10:53
So to get back to this again -- this issue is fixed om my computer if I do the little edit that I wrote in the previous comment. Otherwise it does not work. What do you think?

**Comment by lmcinnes** [comment] 2020-05-16 21:58
Yeah, that looks right. Sorry I've been busy lately. I'll try to get this fixed properly soon.

**Comment by dkobak** [comment] 2020-05-23 12:47
No problem. Maybe re-open the issue in the meanwhile, so that it stays visible. Or I can open a new issue for this, if it's more convenient.

**Comment by lmcinnes** [comment] 2020-05-23 20:29
I believe I just merged a pull request from someone else fixing this, so it should be good now.

**Comment by dkobak** [comment] 2020-05-23 20:32
Great! Cheers.
