### ISSUE TITLE
UMAP for regression

### ISSUE THREAD

**Issue by lcrmorin** [lmcinnes/umap#257] opened 2019-06-20 17:47 UTC
From my understanding UMAP is a fast unsupervised dimension reduction technique. I am personnaly interested in scalable supervised probabilistic models for unbalanced classes.

I had some occasions to play with UMAP for data visualisation purposes (which led to deeper work on anomalies). I have been astounded by the result and, more importantly, by its efficiency and scalability. Still struggling to grasp all the concepts of topological data analysis, I was wondering if it would be possible / make sense to use UMAP in the following ways:

1) As an encoder tool, not necessarily reducing the dimension. The idea is to apply umap while keeping the number of dimension constant. Unsupervisingly reducing dimension can be tricky with unbalanced class (for exemple in Applied Predictive Modelling Kuhn & Jhonson advise to switch from PCA to Partial Least Square - which is essentialy a supervised version of PCA). Is an application of umap without reducing the dimension of the data likely to help improve performance of probabilistic models for unbalanced classes ? (from my experiments with simple models on tabular data, the answer seems to be : not significantly)

2) As a supervised tool. I tried different ways to include the unbalanced binary output in my data without much sucess. Any idea on how to modify umap to use it as a supervised dimension reduction technique while preserving meaningfull relationships between variables and outputs (like PLS is the supervised version of PCA) ?

3) Still on the topic of probabilistic models for unbalanced classes, I have tried to embed the majority class in the space where the minority class has a uniform distribution. The idea is to estimate the density of the whole population in a space of constant density for the minority class. The probability of being in the minority class would then be given by the ratio of the easy to determine constant minority density over the easy to estimate overall density. It seems to work on simple exemples, but I have a hard time dealing with data domains (data from the majority class will fall out of the minority class data domain in the space where they are uniformly distributed. Any hint on how to make that work ?

**Comment by adelejackson** [comment] 2019-06-21 00:28
I can't speak to most of this, but as to (2), have you tried using the [inbuilt supervised tool?](https://umap-learn.readthedocs.io/en/latest/supervised.html) The API is the scikit-learn standard umap.UMAP().fit(data, y=target). The main other relevant argument is target_weight, which controls how much importance the metric on the target values is given relative to the metric from the datapoints themselves.

**Comment by lmcinnes** [comment] 2019-06-21 00:51
Thanks for the kind words, and for the questions. Let me see what I can say about each of your points:

1. It is certainly possible to do this -- I don't expect it to be likely to be particularly beneficial.
2. A @adelejackson notes, you can use UMAP in a supervised context. If you specify ``target_metric='l1'`` you can even use it in a regression rather than classification context.
3. I admit that I don't think I really understand your question, of exactly what the intended use case is here. Do you have a worked concrete example with example data to give me a better idea of what you are trying to do?

**Comment by KnutJaegersberg** [comment] 2019-06-28 15:26
I also was interested in the title of this issue. For regression, one can transform (any) regression problem into an ordinal classification problem as suggested here:
https://towardsdatascience.com/simple-trick-to-train-an-ordinal-regression-with-any-classifier-6911183d2a3c

**Comment by sleighsoft** [comment] 2019-09-17 13:53
Closed but marked as Good Reads so it does not get lost.

**Closed by sleighsoft** 2019-09-17 13:53 UTC
Labels: Good Reads
