### ISSUE TITLE
Save and load a model with UMAP

### ISSUE THREAD

**Issue by JeremieGauthier** [lmcinnes/umap#178] opened 2018-12-09 04:04 UTC
I am very curious of knowing how to save and load a model with UMAP.  That package can be used as a new machine learning technique. I was thinking to train and test a dataset with UMAP.

How is it possible to save and load a model with UMAP?

**Comment by lmcinnes** [comment] 2018-12-09 15:49
I should work just like other scikit-learn modesl, and you can ideally
simply pickle and unpickle the estimator. Potentially you may want to use
joblib dump and load instead as it will be a little more robust in dealing
with large numpy arrays etc.

**Comment by dylanking42** [comment] 2018-12-18 17:51
How about this? 

```
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

X = digits.data
y = digits.target

import umap

reducer = umap.UMAP()

embedding = reducer.fit_transform(X, y)
print(embedding.shape)
# (1797, 2)

import joblib
filename = 'this_is_a_test.sav'
joblib.dump(reducer, filename)

#time passes 
loaded_reducer = joblib.load(filename)

print(type(loaded_reducer))
# <class 'umap.umap_.UMAP'>

# with pickle
import pickle

f_name = 'saving_example.sav'
pickle.dump(reducer, open(f_name, 'wb'))

# time passes
loaded_model = pickle.load((open(f_name, 'rb')))
print(type(loaded_model))
# <class 'umap.umap_.UMAP'>
```
Probably best added to one of the example notebooks.

As always, incredible stuff @lmcinnes

**Comment by JeremieGauthier** [comment] 2018-12-18 17:53
I have already found both option, but thanks for your time @dylanking42 :D

**Comment by dylanking42** [comment] 2018-12-18 19:19
No worries buddy, probably can close this issue then unless anyone wants to copy paste it onto one of the notebooks that already exists.

**Comment by herrmann** [comment] 2019-02-02 17:44
I got a >1GB file that even depends on PySpark when I pickled the UMAP instance directly... is there a list of object properties needed for transformation somewhere?

**Comment by lmcinnes** [comment] 2019-02-02 19:55
@herrmann Sorry, I haven't gotten that well documented yet. Right now the best case is looking through the transform method code itself at what gets used; not ideal, but it is what is available right now.

**Comment by tracek** [comment] 2019-03-31 12:14
@lmcinnes The models I made are at very least 3 GB, with 5 GB being the average. They're made with 150 features and 50 GB data set. I am making an open source software to help conservation scientists in classification of birds from audio recordings. It's a web tool that should allow a user to select a model. Now, we models that big the user experience will be poor.

Any way to slim down the model size? I am using joblib with reasonable compression. I don't get why the models are that enormous. Why model should depend on @herrmann PySpark? 

@herrmann Have you gotten this to work, i.e. the slice of model needed for transform only?

@lmcinnes I will be happy to contribute by documenting what's neeeded or building export functionality. If you have any tips please shoot - thanks.

**Comment by lmcinnes** [comment] 2019-03-31 14:04
The model is much like a knn classifier model; it needs the original data, and that's a large part of what makes it so big. I don't think there are any immediate solutions for that. Longer term I may eventually have some answers, but that is not something that will be implemented any time soon (the theory still has to be worked out, let alone making it practical). Sadly I would suggest that if you need a slim model you will need something simpler like PCA. Sorry I can't be more help.

**Comment by duhaime** [comment] 2019-07-17 14:10
@tracek I wonder if passing in / preserving data with smaller float precision (like `np.around(X, 3)`) would help slim things down? I'm not sure how those numbers are stored on disk, but in the case of web assets that kind of truncation helps quite a bit...

**Comment by dewshr** [comment] 2019-09-05 20:19
I am able to save the model but I am getting an error while loading it. I am using scimitar-learn (0.20.3)

`reducer = joblib.load('reducer_umap_jl_sc.sav')
  File "/home/dshresth/.conda/envs/py27/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/dshresth/.conda/envs/py27/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/home/dshresth/.conda/envs/py27/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/dshresth/.conda/envs/py27/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
  File "/home/dshresth/.conda/envs/py27/lib/python2.7/site-packages/funcsigs/__init__.py", line 201, in __new__
    obj._name = kwargs['name']
KeyError: 'name'`

**Comment by dewshr** [comment] 2019-09-05 21:50
> I am able to save the model but I am getting an error while loading it. I am using scimitar-learn (0.20.3)
> 
> `reducer = joblib.load('reducer_umap_jl_sc.sav') File "/home/dshresth/.conda/envs/py27/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load obj = _unpickle(fobj, filename, mmap_mode) File "/home/dshresth/.conda/envs/py27/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle obj = unpickler.load() File "/home/dshresth/.conda/envs/py27/lib/python2.7/pickle.py", line 864, in load dispatch[key](self) File "/home/dshresth/.conda/envs/py27/lib/python2.7/pickle.py", line 1089, in load_newobj obj = cls.__new__(cls, *args) File "/home/dshresth/.conda/envs/py27/lib/python2.7/site-packages/funcsigs/__init__.py", line 201, in __new__ obj._name = kwargs['name'] KeyError: 'name'`

changing the python version to 3.6 solved it.

**Closed** 2019-09-05 22:45 UTC

**Comment by jmirats** [comment] 2020-05-07 14:27
I'm having troubles when loading a previously saved UMAP model.
I used umap version 0.4.2
The model I construct calls umap as:
mapper = umap.UMAP(n_neighbors=150, n_components=2, metric='cosine',                    random_state=69, transform_queue_size=8.0, min_dist=0.0, target_weight=1,                      target_n_neighbors=20, verbose=True).fit(nzDense_norm,y=labels_train)

nzDense_norm is 290000x4096 numpy float32 matrix
labels_train is 290000 numpy int8 vector

The model is computed correctly and I save it using joblib:
outputFile = open(filename, 'wb')
joblib.dump(mapper, outputFile, compress=True)
outputFile.close()

Then, when I tried to load it using:
mapper = joblib.load(filename)


I get the error below, (which has been reported in #179 but once the model has been loaded)
Any clues or help?
In fact I performed this operation a lot of times with umap-learn 0.3.10 without any trouble. Afterwards, to get 0.4.2 running I needed to install pynndescent (which I did no thave when using 0.3.10) because I was experiencing RAM problems. But now the models are correctly done, but there is this problem of loading it once saved into disk.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 342, in load_build
    Unpickler.load_build(self)
  File "/usr/lib/python3.6/pickle.py", line 1507, in load_build
    setstate(state)
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/pynndescent/pynndescent_.py", line 1026, in __setstate__
    self._rp_forest = tuple([renumbaify_tree(tree) for tree in d["_rp_forest"]])
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/pynndescent/pynndescent_.py", line 1026, in <listcomp>
    self._rp_forest = tuple([renumbaify_tree(tree) for tree in d["_rp_forest"]])
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/pynndescent/rp_trees.py", line 1178, in renumbaify_tree
    hyperplanes.extend(tree.hyperplanes)
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/typed/typedlist.py", line 302, in extend
    return _extend(self, iterable)
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function impl_extend at 0x7f97dcd35950>) with argument(s) of type(s): (ListType[array(float64, 2d, C)], reflected list(array(float32, 1d, C)))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function impl_append at 0x7f97dcd350d0>) with argument(s) of type(s): (ListType[array(float64, 2d, C)], array(float32, 1d, C))
 * parameterized
In definition 0:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "../../Trainer/lib/python3.6/site-packages/numba/listobject.py", line 487:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^

[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, listobject.py:487), Var($0.3, listobject.py:487)], kws=(), vararg=None)" at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/listobject.py (487)
    raised from /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/six.py:669
In definition 1:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "../../Trainer/lib/python3.6/site-packages/numba/listobject.py", line 487:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^

[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, listobject.py:487), Var($0.3, listobject.py:487)], kws=(), vararg=None)" at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/listobject.py (487)
    raised from /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/six.py:669
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'append') for ListType[array(float64, 2d, C)])
[2] During: typing of call at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/listobject.py (895)


File "../../Trainer/lib/python3.6/site-packages/numba/listobject.py", line 895:
            def impl(l, iterable):
                <source elided>
                for i in iterable:
                    l.append(i)
                    ^

    raised from /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/typeinfer.py:985
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function impl_append at 0x7f97dcd350d0>) with argument(s) of type(s): (ListType[array(float64, 2d, C)], array(float32, 1d, C))
 * parameterized
In definition 0:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "../../Trainer/lib/python3.6/site-packages/numba/listobject.py", line 487:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^

[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, listobject.py:487), Var($0.3, listobject.py:487)], kws=(), vararg=None)" at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/listobject.py (487)
    raised from /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/six.py:669
In definition 1:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "../../Trainer/lib/python3.6/site-packages/numba/listobject.py", line 487:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^

[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, listobject.py:487), Var($0.3, listobject.py:487)], kws=(), vararg=None)" at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/listobject.py (487)
    raised from /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/six.py:669
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'append') for ListType[array(float64, 2d, C)])
[2] During: typing of call at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/listobject.py (895)


File "../../Trainer/lib/python3.6/site-packages/numba/listobject.py", line 895:
            def impl(l, iterable):
                <source elided>
                for i in iterable:
                    l.append(i)
                    ^

    raised from /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/typeinfer.py:985
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'extend') for ListType[array(float64, 2d, C)])
[2] During: typing of call at /home/peppone/Feina/INLOC/Projectes/WorkDir/Trainer/lib/python3.6/site-packages/numba/typed/typedlist.py (82)


File "../../Trainer/lib/python3.6/site-packages/numba/typed/typedlist.py", line 82:
def _extend(l, iterable):
    return l.extend(iterable)
    ^

**Comment by Miladiouss** [comment] 2023-11-11 01:06
> How about this?
> 
> ```
> import numpy as np
> from sklearn.datasets import load_digits
> 
> digits = load_digits()
> 
> X = digits.data
> y = digits.target
> 
> import umap
> 
> reducer = umap.UMAP()
> 
> embedding = reducer.fit_transform(X, y)
> print(embedding.shape)
> # (1797, 2)
> 
> import joblib
> filename = 'this_is_a_test.sav'
> joblib.dump(reducer, filename)
> 
> #time passes 
> loaded_reducer = joblib.load(filename)
> 
> print(type(loaded_reducer))
> # <class 'umap.umap_.UMAP'>
> 
> # with pickle
> import pickle
> 
> f_name = 'saving_example.sav'
> pickle.dump(reducer, open(f_name, 'wb'))
> 
> # time passes
> loaded_model = pickle.load((open(f_name, 'rb')))
> print(type(loaded_model))
> # <class 'umap.umap_.UMAP'>
> ```
> 
> Probably best added to one of the example notebooks.
> 
> As always, incredible stuff @lmcinnes

This makes it OS and environment dependent.
